const tracks=[
 {title:'Midnight Pulse',artist:'VIX Selection',cover:'https://picsum.photos/seed/vix1/700/700',url:'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3'},
 {title:'Neon Dreams',artist:'Nova',cover:'https://picsum.photos/seed/vix2/700/700',url:'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3'},
 {title:'Afterglow',artist:'Velvet',cover:'https://picsum.photos/seed/vix3/700/700',url:'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3'},
 {title:'City Lights',artist:'Neon Sky',cover:'https://picsum.photos/seed/vix4/700/700',url:'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3'}
];
const audio=document.querySelector('#audio'), heroCover=document.querySelector('#heroCover'),heroTitle=document.querySelector('#heroTitle'),heroArtist=document.querySelector('#heroArtist'),heroPlay=document.querySelector('#heroPlay'),barPlay=document.querySelector('#barPlay'),barCover=document.querySelector('#barCover'),barTitle=document.querySelector('#barTitle'),barArtist=document.querySelector('#barArtist'),progress=document.querySelector('#heroProgress'),currentTime=document.querySelector('#currentTime'),duration=document.querySelector('#duration'),barTime=document.querySelector('#barTime');
let current=0;
const fmt=s=>{if(!Number.isFinite(s))return'0:00';const m=Math.floor(s/60),sec=Math.floor(s%60).toString().padStart(2,'0');return`${m}:${sec}`};
function load(i,autoplay=false){current=(i+tracks.length)%tracks.length;const t=tracks[current];audio.src=t.url;heroCover.src=t.cover;barCover.src=t.cover;heroTitle.textContent=t.title;heroArtist.textContent=t.artist;barTitle.textContent=t.title;barArtist.textContent=t.artist;progress.style.width='0%';if(autoplay)audio.play().catch(()=>{});updateButtons()}
function updateButtons(){const playing=!audio.paused;heroPlay.textContent=playing?'Ⅱ':'▶';barPlay.textContent=playing?'Ⅱ':'▶'}
function toggle(){if(audio.paused)audio.play().catch(()=>{});else audio.pause()}
heroPlay.onclick=toggle;barPlay.onclick=toggle;document.querySelector('#prevBtn').onclick=()=>load(current-1,true);document.querySelector('#nextBtn').onclick=()=>load(current+1,true);document.querySelector('#muteBtn').onclick=()=>{audio.muted=!audio.muted;document.querySelector('#muteBtn').textContent=audio.muted?'◉':'◖'};
audio.addEventListener('play',updateButtons);audio.addEventListener('pause',updateButtons);audio.addEventListener('loadedmetadata',()=>duration.textContent=fmt(audio.duration));audio.addEventListener('timeupdate',()=>{const p=audio.duration?(audio.currentTime/audio.duration)*100:0;progress.style.width=p+'%';currentTime.textContent=fmt(audio.currentTime);barTime.textContent=`${fmt(audio.currentTime)} / ${fmt(audio.duration)}`});audio.addEventListener('ended',()=>load(current+1,true));
const list=document.querySelector('#trackList');tracks.forEach((t,i)=>{const el=document.createElement('div');el.className='track';el.innerHTML=`<img class="track-cover" src="${t.cover}" alt=""><div class="track-info"><strong>${t.title}</strong><span>${t.artist}</span></div><span class="track-time">VIX</span>`;el.onclick=()=>load(i,true);list.appendChild(el)});
document.querySelectorAll('.playlist-card').forEach(card=>card.addEventListener('click',()=>load(Number(card.dataset.track),true)));
document.querySelectorAll('.mode').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));btn.classList.add('active')}));
const overlay=document.querySelector('#searchOverlay'),input=document.querySelector('#searchInput'),results=document.querySelector('#searchResults');document.querySelector('#searchTrigger').onclick=()=>{overlay.classList.add('open');overlay.setAttribute('aria-hidden','false');setTimeout(()=>input.focus(),50)};document.querySelector('#closeSearch').onclick=()=>{overlay.classList.remove('open');overlay.setAttribute('aria-hidden','true')};overlay.addEventListener('click',e=>{if(e.target===overlay)document.querySelector('#closeSearch').click()});input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();if(!q){results.innerHTML='<p class="muted">Начни вводить запрос</p>';return}const found=tracks.filter(t=>(t.title+' '+t.artist).toLowerCase().includes(q));results.innerHTML=found.length?found.map((t,i)=>`<div class="result" data-i="${tracks.indexOf(t)}"><img src="${t.cover}" alt=""><div><strong>${t.title}</strong><span>${t.artist}</span></div></div>`).join(''):'<p class="muted">Ничего не найдено</p>';results.querySelectorAll('.result').forEach(x=>x.onclick=()=>{load(Number(x.dataset.i),true);document.querySelector('#closeSearch').click()})});
document.querySelector('#heroLike').onclick=e=>{e.currentTarget.classList.toggle('liked');e.currentTarget.textContent=e.currentTarget.classList.contains('liked')?'♥':'♡'};
document.querySelectorAll('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{if(btn.dataset.section){document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active');if(btn.dataset.section==='home')window.scrollTo({top:0,behavior:'smooth'});else if(btn.dataset.section==='playlists')document.querySelector('#recommendedPlaylists').scrollIntoView({behavior:'smooth'});else document.querySelector('#trackList').scrollIntoView({behavior:'smooth'})}}));
const bottomNav=document.querySelector('.bottom-nav');let lastScrollY=window.scrollY;let scrollTick=false;function updateBottomNav(){const y=window.scrollY;if(Math.abs(y-lastScrollY)<6){scrollTick=false;return}if(y>lastScrollY&&y>80)bottomNav?.classList.add('nav-hidden');else if(y<lastScrollY)bottomNav?.classList.remove('nav-hidden');if(y<=20)bottomNav?.classList.remove('nav-hidden');lastScrollY=y;scrollTick=false}window.addEventListener('scroll',()=>{if(!scrollTick){requestAnimationFrame(updateBottomNav);scrollTick=true}},{passive:true});
load(0,false);
